from __future__ import annotations

NTFS_SIGNATURE = 0xAA55
NTFS_OEM_ID = b"NTFS    "

FILE_RECORD_SIGNATURE = b"FILE"
INDX_RECORD_SIGNATURE = b"INDX"
CHKD_RECORD_SIGNATURE = b"CHKD"
BAAD_RECORD_SIGNATURE = b"BAAD"

MFT_RECORD_IN_USE = 0x0001
MFT_RECORD_IS_DIRECTORY = 0x0002
MFT_RECORD_IS_EXTENSION = 0x0004
MFT_RECORD_IN_USE_MASK = 0x0001
MFT_RECORD_DELETED = 0x0000

ATTR_STANDARD_INFORMATION = 0x10
ATTR_ATTRIBUTE_LIST = 0x20
ATTR_FILE_NAME = 0x30
ATTR_OBJECT_ID = 0x40
ATTR_SECURITY_DESCRIPTOR = 0x50
ATTR_VOLUME_NAME = 0x60
ATTR_VOLUME_INFORMATION = 0x70
ATTR_DATA = 0x80
ATTR_INDEX_ROOT = 0x90
ATTR_INDEX_ALLOCATION = 0xA0
ATTR_BITMAP = 0xB0
ATTR_REPARSE_POINT = 0xC0
ATTR_EA_INFORMATION = 0xD0
ATTR_EA = 0xE0
ATTR_LOGGED_UTILITY_STREAM = 0x100

ATTR_NAMES: dict[int, str] = {
    0x10: "STANDARD_INFORMATION",
    0x20: "ATTRIBUTE_LIST",
    0x30: "FILE_NAME",
    0x40: "OBJECT_ID",
    0x50: "SECURITY_DESCRIPTOR",
    0x60: "VOLUME_NAME",
    0x70: "VOLUME_INFORMATION",
    0x80: "DATA",
    0x90: "INDEX_ROOT",
    0xA0: "INDEX_ALLOCATION",
    0xB0: "BITMAP",
    0xC0: "REPARSE_POINT",
    0xD0: "EA_INFORMATION",
    0xE0: "EA",
    0x100: "LOGGED_UTILITY_STREAM",
}

ATTR_FLAG_COMPRESSED = 0x0001
ATTR_FLAG_ENCRYPTED = 0x4000
ATTR_FLAG_SPARSE = 0x8000
ATTR_FLAG_NON_RESIDENT = 0x8000_0000_0000_0001

FILE_NAME_POSIX = 0
FILE_NAME_WIN32 = 1
FILE_NAME_DOS = 2
FILE_NAME_WIN32_AND_DOS = 3

FIXUP_SIGNATURE = 0x2A

STANDARD_INFO_HEADER_SIZE = 72
FILE_NAME_HEADER_SIZE = 68

MFT_IDX_ROOT = 0
MFT_IDX_MFTMIRR = 1
MFT_IDX_LOGFILE = 2
MFT_IDX_VOLUME = 3
MFT_IDX_ATTRDEF = 4
MFT_IDX_ROOT = 5
MFT_IDX_BITMAP = 6
MFT_IDX_BOOT = 7
MFT_IDX_BADCLUS = 8
MFT_IDX_SECURE = 9
MFT_IDX_UP = 10
MFT_IDX_EXTEND = 11

MFT_RESERVED_RECORDS = 16
